export default [
  {
    id: 1,
    name: 'openTTD',
    description:
      'OpenTTD is an open-source simulation game based upon the popular Microprose game "Transport Tycoon Deluxe", written by Chris Sawyer. It attempts to mimic the original game as closely as possible while extending it with new features.',
    icon: 'https://placehold.co/500x500/red/white',
    banner: 'https://placehold.co/1000x500/red/white',
    boxArt: 'https://placehold.co/300x400/red/white',
    type: 'zip',
    selectedArchive: 1,
    archives: [
      {
        id: 1,
        name: 'archive1',
        version: '1.32',
        os: 'windows',
        isInstalled: true,
        file: 'http://localhost:3000/files/openttd-14.1-linux-generic-amd64.zip'
      },
      {
        id: 2,
        name: 'archive2',
        version: '1.32',
        os: 'linux',
        isInstalled: false,
        file: 'http://localhost:3000/files/openttd-14.1-linux-generic-amd64.zip'
      },
      {
        id: 3,
        name: 'archive3',
        version: '1.32',
        os: 'mac',
        isInstalled: false,
        file: 'http://localhost:3000/files/openttd-14.1-linux-generic-amd64.zip'
      },
    ],
  },
  {
    id: 2,
    name: 'Cyberpunk 2077',
    description:
      'An open-world, action-adventure RPG set in the megalopolis of Night City.',
    icon: 'https://placehold.co/500x500/blue/white',
    banner: 'https://placehold.co/1000x500/blue/white',
    boxArt: 'https://placehold.co/300x400/blue/white',
    type: 'zip',
    selectedArchive: 1,
    archives: [
      {
        id: 1,
        name: 'archive1',
        version: '2.1',
        os: 'windows',
        isInstalled: true,
      },
      {
        id: 2,
        name: 'archive2',
        version: '2.1',
        os: 'linux',
        isInstalled: false,
      },
      {
        id: 3,
        name: 'archive3',
        version: '2.1',
        os: 'mac',
        isInstalled: false,
      },
    ],
  },
  {
    id: 3,
    name: 'Red Dead Redemption 2',
    description:
      'An epic tale of life in America’s unforgiving heartland. The game’s vast and atmospheric world will also provide the foundation for a brand new online multiplayer experience.',
    icon: 'https://placehold.co/500x500/green/white',
    banner: 'https://placehold.co/1000x500/green/white',
    boxArt: 'https://placehold.co/300x400/green/white',
    type: 'zip',
    selectedArchive: 1,
    archives: [
      {
        id: 1,
        name: 'archive1',
        version: '1.0',
        os: 'windows',
        isInstalled: true,
      },
      {
        id: 2,
        name: 'archive2',
        version: '1.0',
        os: 'linux',
        isInstalled: false,
      },
      {
        id: 3,
        name: 'archive3',
        version: '1.0',
        os: 'mac',
        isInstalled: false,
      },
    ],
  },
  {
    id: 4,
    name: 'Grand Theft Auto V',
    description:
      'When a young street hustler, a retired bank robber and a terrifying psychopath find themselves entangled with some of the most frightening and deranged elements of the criminal underworld, the U.S. government and the entertainment industry, they must pull off a series of dangerous heists to survive in a ruthless city in which they can trust nobody, least of all each other.',
    icon: 'https://placehold.co/500x500/yellow/black',
    banner: 'https://placehold.co/1000x500/yellow/black',
    boxArt: 'https://placehold.co/300x400/yellow/black',
    type: 'zip',
    selectedArchive: 1,
    archives: [
      {
        id: 1,
        name: 'archive1',
        version: '1.0',
        os: 'windows',
        isInstalled: true,
      },
      {
        id: 2,
        name: 'archive2',
        version: '1.0',
        os: 'linux',
        isInstalled: false,
      },
      {
        id: 3,
        name: 'archive3',
        version: '1.0',
        os: 'mac',
        isInstalled: false,
      },
    ],
  },
  {
    id: 5,
    name: 'Elden Ring',
    description:
      'Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring and become an Elden Lord in the Lands Between.',
    icon: 'https://placehold.co/500x500/purple/white',
    banner: 'https://placehold.co/1000x500/purple/white',
    boxArt: 'https://placehold.co/300x400/purple/white',
    type: 'zip',
    selectedArchive: 1,
    archives: [
      {
        id: 1,
        name: 'archive1',
        version: '1.0',
        os: 'windows',
        isInstalled: true,
      },
      {
        id: 2,
        name: 'archive2',
        version: '1.0',
        os: 'linux',
        isInstalled: false,
      },
      {
        id: 3,
        name: 'archive3',
        version: '1.0',
        os: 'mac',
        isInstalled: false,
      },
    ],
  },
  {
    id: 6,
    name: 'God of War',
    description:
      'It is a new beginning for Kratos. Living as a man outside the shadow of the gods, he must adapt to the unfamiliar Norse lands, unexpected threats, and a second chance at being a father. Together with his son Atreus, he will venture into the brutal Norse wilds and fight to fulfill a deeply personal quest.',
    icon: 'https://placehold.co/500x500/orange/black',
    banner: 'https://placehold.co/1000x500/orange/black',
    boxArt: 'https://placehold.co/300x400/orange/black',
    type: 'zip',
    selectedArchive: 1,
    archives: [
      {
        id: 1,
        name: 'archive1',
        version: '1.0',
        os: 'windows',
        isInstalled: true,
      },
      {
        id: 2,
        name: 'archive2',
        version: '1.0',
        os: 'linux',
        isInstalled: false,
      },
      {
        id: 3,
        name: 'archive3',
        version: '1.0',
        os: 'mac',
        isInstalled: false,
      },
    ],
  },
  {
    id: 7,
    name: 'Marvel’s Spider-Man',
    description:
      'In Marvel’s Spider-Man Remastered, Peter Parker is fighting big crime and petty criminals in Marvel’s New York. At the same time, he’s struggling to balance his chaotic personal life and career while the fate of Marvel’s New York rests upon his shoulders.',
    icon: 'https://placehold.co/500x500/cyan/black',
    banner: 'https://placehold.co/1000x500/cyan/black',
    boxArt: 'https://placehold.co/300x400/cyan/black',
    type: 'zip',
    selectedArchive: 1,
    archives: [
      {
        id: 1,
        name: 'archive1',
        version: '1.0',
        os: 'windows',
        isInstalled: true,
      },
      {
        id: 2,
        name: 'archive2',
        version: '1.0',
        os: 'linux',
        isInstalled: false,
      },
      {
        id: 3,
        name: 'archive3',
        version: '1.0',
        os: 'mac',
        isInstalled: false,
      },
    ],
  },
  {
    id: 8,
    name: 'Hogwarts Legacy',
    description:
      'Hogwarts Legacy is an immersive, open-world action RPG set in the 1800s wizarding world. Beginning as a fifth year, players will embark on a journey through familiar and new locations, discover fantastic beasts, customize their character, brew potions, master spell casting, upgrade talents and become the wizard they want to be.',
    icon: 'https://placehold.co/500x500/lime/black',
    banner: 'https://placehold.co/1000x500/lime/black',
    boxArt: 'https://placehold.co/300x400/lime/black',
    type: 'zip',
    selectedArchive: 1,
    archives: [
      {
        id: 1,
        name: 'archive1',
        version: '1.0',
        os: 'windows',
        isInstalled: true,
      },
      {
        id: 2,
        name: 'archive2',
        version: '1.0',
        os: 'linux',
        isInstalled: false,
      },
      {
        id: 3,
        name: 'archive3',
        version: '1.0',
        os: 'mac',
        isInstalled: false,
      },
    ],
  },
  {
    id: 9,
    name: 'The Last of Us Part I',
    description:
      'In a ravaged civilization, where infected and hardened survivors run rampant, Joel, a weary protagonist, is hired to smuggle 14-year-old Ellie out of a military quarantine zone. However, what starts as a small job soon transforms into a brutal cross-country journey.',
    icon: 'https://placehold.co/500x500/pink/black',
    banner: 'https://placehold.co/1000x500/pink/black',
    boxArt: 'https://placehold.co/300x400/pink/black',
    type: 'zip',
    selectedArchive: 1,
    archives: [
      {
        id: 1,
        name: 'archive1',
        version: '1.0',
        os: 'windows',
        isInstalled: true,
      },
      {
        id: 2,
        name: 'archive2',
        version: '1.0',
        os: 'linux',
        isInstalled: false,
      },
      {
        id: 3,
        name: 'archive3',
        version: '1.0',
        os: 'mac',
        isInstalled: false,
      },
    ],
  },
  {
    id: 10,
    name: 'Resident Evil 4',
    description:
      'Survival is just the beginning. Six years have passed since the biological disaster in Raccoon City. Leon S. Kennedy, one of the survivors of the incident, has been sent to rescue Dr. Ashley Graham, the president’s daughter, who has been kidnapped.',
    icon: 'https://placehold.co/500x500/teal/white',
    banner: 'https://placehold.co/1000x500/teal/white',
    boxArt: 'https://placehold.co/300x400/teal/white',
    type: 'steam',

  },
];

